<?php
/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
$this->placeholder('url')->delete = $this->urlDelete;
?>
<h1>Maiores Usuários de Software Livre</h1>
<table>
<thead>
<tr>
<th>Usuário</th>
<th>&nbsp;</th>
<th>Quantidade</th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('maiores-usuarios.phtml',$this->paginator)?>
</tbody>
</table>
<p>
<?=$this->paginationControl($this->paginator,
'Sliding',
'pagination', ['route' => 'maior-usuario']); ?>
</p>
<p>
<a href="<?=$this->url('home')?>">Homepage</a>
</p>