<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
	<h1 class="display-4">Cadastros</h1>
	<table>
		<tr>
			<td>
				<ul>
					<li><a
						href="<?=$this->url('application',['controller' => 'orgao'])?>">Órgão</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'tipo-de-orgao'])?>">Tipos
							de Órgão</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'software'])?>">Software</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'categoria-de-software'])?>">Categorias
							de Software</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'licenca'])?>">Licença</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'protocolo'])?>">Protocolo</a></li>

				</ul>
			</td>
			<td>
				<ul>
					<li><a
						href="<?=$this->url('application',['controller' => 'software-de-orgao'])?>">Softwares
							de um órgão</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'protocolo-de-orgao'])?>">Protocolos
							de um órgão</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'maior-orgao-usuario'])?>">Maiores Órgãos
							Usuários de Software Livre</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'maior-tipo-orgao-usuario'])?>">Maiores
							Tipos de Órgãos Usuários de Software Livre</a></li>							
					<li><a
						href="<?=$this->url('application',['controller' => 'indicador'])?>">Indicadores
							Gerais</a></li>
				</ul>
			</td>
			<td>
				<ul>
					<li><a
						href="<?=$this->url('application',['controller' => 'software-mais-usado'])?>">Software
							Livres Mais Usados </a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'licenca-mais-usada'])?>">Licenças
							Livres Mais Usadas </a></li>			
					<li><a
						href="<?=$this->url('application',['controller' => 'categoria-mais-usada'])?>">Categorias de Softwares
							Livres Mais Usadas</a></li>
					<li><a
						href="<?=$this->url('application',['controller' => 'software-nao-livre-mais-usado'])?>">Softwares Não Livres Mais Usados
							</a></li>
				</ul>
			</td>			
		</tr>
	</table>

</div>
